name: Update tested third party versions

on:
  workflow_dispatch:

env:
  # Set the GRADLE_ENTERPRISE_ACCESS_KEY so that Gradle Build Scans are generated
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  # Enable debug for the `gradle-build-action` cache operations
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  update-tested-versions:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: assemble
        uses: gradle/gradle-build-action@v2
      - name: update-tested-versions
        run: ./gradlew --no-configuration-cache updateAgpVersions updateKotlinVersions
      - run: git status
